ALTER TABLE cup
  ADD COLUMN has_toilets BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN has_food BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN has_parking BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN map_url TEXT NOT NULL DEFAULT '';
